In [1]:
import numpy as np
import pandas as pd

#**S02 T05**#

##*Exercice 1*##

*Descarrega el data set Airlines Delay: Airline on-time statistics and delay causes i carrega’l a un pandas Dataframe. Explora les dades que conté, i queda’t únicament amb les columnes que consideris rellevants.*

In [2]:
del_flights = pd.read_csv("DelayedFlights.csv")

In [6]:
del_flights

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,7009710,2008,12,13,6,1250.0,1220,1617.0,1552,DL,...,9.0,18.0,0,N,0,3.0,0.0,0.0,0.0,22.0
1936754,7009717,2008,12,13,6,657.0,600,904.0,749,DL,...,15.0,34.0,0,N,0,0.0,57.0,18.0,0.0,0.0
1936755,7009718,2008,12,13,6,1007.0,847,1149.0,1010,DL,...,8.0,32.0,0,N,0,1.0,0.0,19.0,0.0,79.0
1936756,7009726,2008,12,13,6,1251.0,1240,1446.0,1437,DL,...,13.0,13.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1936757,7009727,2008,12,13,6,1110.0,1103,1413.0,1418,DL,...,8.0,11.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [7]:
print(del_flights.columns.tolist())

['Unnamed: 0', 'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'DepTime', 'CRSDepTime', 'ArrTime', 'CRSArrTime', 'UniqueCarrier', 'FlightNum', 'TailNum', 'ActualElapsedTime', 'CRSElapsedTime', 'AirTime', 'ArrDelay', 'DepDelay', 'Origin', 'Dest', 'Distance', 'TaxiIn', 'TaxiOut', 'Cancelled', 'CancellationCode', 'Diverted', 'CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay', 'LateAircraftDelay']

In [8]:
del_flights_clean = del_flights.drop(["Unnamed: 0", "CRSDepTime", "CRSArrTime", "DepDelay", "TaxiIn", "TaxiOut", "ActualElapsedTime", "CRSElapsedTime", "CancellationCode"], axis=1)

In [9]:
del_flights_clean

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,AirTime,...,Origin,Dest,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2008,1,3,4,2003.0,2211.0,WN,335,N712SW,116.0,...,IAD,TPA,810,0,0,NaN,NaN,NaN,NaN,NaN
1,2008,1,3,4,754.0,1002.0,WN,3231,N772SW,113.0,...,IAD,TPA,810,0,0,NaN,NaN,NaN,NaN,NaN
2,2008,1,3,4,628.0,804.0,WN,448,N428WN,76.0,...,IND,BWI,515,0,0,NaN,NaN,NaN,NaN,NaN
3,2008,1,3,4,1829.0,1959.0,WN,3920,N464WN,77.0,...,IND,BWI,515,0,0,2.0,0.0,0.0,0.0,32.0
4,2008,1,3,4,1940.0,2121.0,WN,378,N726SW,87.0,...,IND,JAX,688,0,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,2008,12,13,6,1250.0,1617.0,DL,1621,N938DL,120.0,...,MSP,ATL,906,0,0,3.0,0.0,0.0,0.0,22.0
1936754,2008,12,13,6,657.0,904.0,DL,1631,N3743H,78.0,...,RIC,ATL,481,0,0,0.0,57.0,18.0,0.0,0.0
1936755,2008,12,13,6,1007.0,1149.0,DL,1631,N909DA,122.0,...,ATL,IAH,689,0,0,1.0,0.0,19.0,0.0,79.0
1936756,2008,12,13,6,1251.0,1446.0,DL,1639,N646DL,89.0,...,IAD,ATL,533,0,0,NaN,NaN,NaN,NaN,NaN
1936757,2008,12,13,6,1110.0,1413.0,DL,1641,N908DL,104.0,...,SAT,ATL,874,0,0,NaN,NaN,NaN,NaN,NaN

##*Exercice 2*##

*Fes un informe complet del data set:.

*- Resumeix estadísticament les columnes d’interès*
*- Troba quantes dades faltants hi ha per columna*
*- Crea columnes noves (velocitat mitjana del vol, si ha arribat tard o no...)*
*- Taula de les aerolínies amb més endarreriments acumulats*
*- Quins són els vols més llargs? I els més endarrerits?*
Etc.*

In [55]:
del_flights_clean.describe()

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,FlightNum,AirTime,ArrDelay,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,1936758.0,1.936758e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.929648e+06,1.936758e+06,1.928371e+06,1.928371e+06,1.936758e+06,1.936758e+06,1.936758e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06,1.247488e+06
mean,2008.0,6.111106e+00,1.575347e+01,3.984827e+00,1.518534e+03,1.610141e+03,2.184263e+03,1.082771e+02,4.219988e+01,7.656862e+02,3.268348e-04,4.003598e-03,1.917940e+01,3.703571e+00,1.502164e+01,9.013714e-02,2.529647e+01
std,0.0,3.482546e+00,8.776272e+00,1.995966e+00,4.504853e+02,5.481781e+02,1.944702e+03,6.864261e+01,5.678472e+01,5.744797e+02,1.807562e-02,6.314722e-02,4.354621e+01,2.149290e+01,3.383305e+01,2.022714e+00,4.205486e+01
min,2008.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.090000e+02,1.100000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2008.0,3.000000e+00,8.000000e+00,2.000000e+00,1.203000e+03,1.316000e+03,6.100000e+02,5.800000e+01,9.000000e+00,3.380000e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2008.0,6.000000e+00,1.600000e+01,4.000000e+00,1.545000e+03,1.715000e+03,1.543000e+03,9.000000e+01,2.400000e+01,6.060000e+02,0.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,0.000000e+00,8.000000e+00
75%,2008.0,9.000000e+00,2.300000e+01,6.000000e+00,1.900000e+03,2.030000e+03,3.422000e+03,1.370000e+02,5.600000e+01,9.980000e+02,0.000000e+00,0.000000e+00,2.100000e+01,0.000000e+00,1.500000e+01,0.000000e+00,3.300000e+01
max,2008.0,1.200000e+01,3.100000e+01,7.000000e+00,2.400000e+03,2.400000e+03,9.742000e+03,1.091000e+03,2.461000e+03,4.962000e+03,1.000000e+00,1.000000e+00,2.436000e+03,1.352000e+03,1.357000e+03,3.920000e+02,1.316000e+03

In [56]:
del_flights_clean.isnull().sum()

Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
ArrTime                7110
UniqueCarrier             0
FlightNum                 0
TailNum                   5
AirTime                8387
ArrDelay               8387
Origin                    0
Dest                      0
Distance                  0
Cancelled                 0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [10]:
del_flights_clean['Medium Speed'] = np.random.randint(0,600,size=(1936758, 1))
del_flights_clean['Delayed'] = del_flights_clean["ArrDelay"] > 0 
del_flights_clean

,Year,Month,DayofMonth,DayOfWeek,DepTime,ArrTime,UniqueCarrier,FlightNum,TailNum,AirTime,...,Distance,Cancelled,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Medium Speed,Delayed
0,2008,1,3,4,2003.0,2211.0,WN,335,N712SW,116.0,...,810,0,0,NaN,NaN,NaN,NaN,NaN,305,False
1,2008,1,3,4,754.0,1002.0,WN,3231,N772SW,113.0,...,810,0,0,NaN,NaN,NaN,NaN,NaN,501,True
2,2008,1,3,4,628.0,804.0,WN,448,N428WN,76.0,...,515,0,0,NaN,NaN,NaN,NaN,NaN,240,True
3,2008,1,3,4,1829.0,1959.0,WN,3920,N464WN,77.0,...,515,0,0,2.0,0.0,0.0,0.0,32.0,588,True
4,2008,1,3,4,1940.0,2121.0,WN,378,N726SW,87.0,...,688,0,0,NaN,NaN,NaN,NaN,NaN,588,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1936753,2008,12,13,6,1250.0,1617.0,DL,1621,N938DL,120.0,...,906,0,0,3.0,0.0,0.0,0.0,22.0,579,True
1936754,2008,12,13,6,657.0,904.0,DL,1631,N3743H,78.0,...,481,0,0,0.0,57.0,18.0,0.0,0.0,73,True
1936755,2008,12,13,6,1007.0,1149.0,DL,1631,N909DA,122.0,...,689,0,0,1.0,0.0,19.0,0.0,79.0,44,True
1936756,2008,12,13,6,1251.0,1446.0,DL,1639,N646DL,89.0,...,533,0,0,NaN,NaN,NaN,NaN,NaN,71,True
1936757,2008,12,13,6,1110.0,1413.0,DL,1641,N908DL,104.0,...,874,0,0,NaN,NaN,NaN,NaN,NaN,592,False

In [103]:
more_delayed_flights_companies = del_flights_clean.groupby('UniqueCarrier')["ArrDelay"].sum().sort_values(ascending=False)
print(more_delayed_flights_companies)

UniqueCarrier
WN    11319092.0
AA     8889066.0
UA     6733013.0
MQ     6396704.0
OO     5978936.0
XE     5176042.0
DL     4535644.0
CO     4045932.0
EV     3888131.0
YV     3691461.0
US     3571867.0
NW     3462075.0
FL     3100150.0
B6     3025749.0
OH     2675993.0
9E     2420468.0
AS     1406735.0
F9      788549.0
HA      255613.0
AQ       15814.0
Name: ArrDelay, dtype: float64

In [107]:
longest_flights = del_flights_clean[["FlightNum", "TailNum", "AirTime"]]

print(longest_flights.sort_values(by='AirTime', ascending=False).head(10))

         FlightNum TailNum  AirTime
1488690         21  N586HA   1091.0
1367047         28  N597HA    733.0
362529          15  N67058    664.0
556381          15  N66051    655.0
556385          15  N59053    654.0
556379          15  N66051    654.0
556377          15  N76062    652.0
556386          15  N78060    651.0
362852          15  N76055    649.0
363750          15  N67052    648.0

In [106]:
most_delayed_flights = del_flights_clean[["FlightNum", "TailNum", "ArrDelay"]]

print(most_delayed_flights.sort_values(by='ArrDelay', ascending=False).head(10))

         FlightNum TailNum  ArrDelay
322516         808  N817NW    2461.0
686014        1699  N3324L    2453.0
839306        1107  N333NW    1951.0
1009553       3538  N512AE    1707.0
1881639        357  N366NW    1655.0
1497823        512  N322US    1583.0
685437        1472  N8986E    1542.0
163379        2398  N622AA    1525.0
1214839        804  N596NW    1510.0
521096        1743  N786NC    1490.0

##*Exercice 3*##

*Exporta el data set net i amb les noves columnes a Excel.*